### ISSUE TITLE
when set action to back, it behaves not as expectation described in official doc

### ISSUE THREAD

**Issue by terryatgithub** [Instawork/hyperview#261]
Hi, it seems that when set action to `back` in hyperview xml, it behaves not as expectation described in doc as below.
In official demo, press button "Back to other", it just goes back to previous page, **does not make a new request to the new url**. 
Please help check, thanks a lot.

[doc to action=back](https://hyperview.org/docs/reference_behavior_attributes#navigate)
> When the user presses "Go to second screen", the second screen will be pushed onto the stack. Then, if the user pushes "Go back", the stack will unwind, and the user will see screen 1 again. **However, if the user pushes "Go back to a different place", the stack will unwind, and Hyperview will make a request to https://mysite.com/third. The content of the first screen will be replaced with the content from the third request.** 
Any change in the URL will cause a reload, including changes in the search string.

**Comment by terryatgithub** [comment]
and so does it when set action to `close`.
I'd like to hear your guys' opinions/comments before I try to follow and fix it. 
thank you so much.

**Comment by adamstep** [comment]
@terryatgithub can you give an example of what you'd like to achieve? Like is says in the documentation:

> If the provided `href` attribute would load data from the **same source** as the previous screen, **no request happens**. However, **if the provided href is different, a request will be made to reload the previous screen**.

So, let's say you open `/screen/a` and then push `screen/b`.
- If the XML says `<text action="back" href="/screen/a">Back</text>`, then Hyperview will un-push the screen but not make a request (because the href `screen/a` is the same as the previous screen's URL).
- If the XML says `<text action="back" href="/screen/c">Back</text>`, then Hyperview iwll un-push the screen and make a request to `/screen/c`.

This is intentional design, usually when users are navigating back in the mobile app, they do not need to re-load the content. However, in some cases you may want to reload the previous screen. There are some options:

- Use a timestamp query parameter in the href: `<text action="back" href="/screen/a?id=12345">Back</text>`. `12345` is the current timestamp when loading the page. That way, each time the user presses back, the previous screen will reload, because `href` will be different.
- Use [event dispatch](https://hyperview.org/docs/example_event_dispatch). The back button will dispatch an event. Screen A listens for the event and will reload itself:
```xml
Screen B:
<text action="back" href="/screen/a?id=12345">
  <behavior action="dispatch-event" event-name="reload-screen-a" />
  Back
</text>

Screen A:
<body>
  <behavior trigger="on-event" event-name="reload-screen-a" action="reload" />
  ...
</body>
```

**Comment by adamstep** [comment]
Hi @terryatgithub , you are right. The "Back to other" does not work for me in demo app. It does work in the Instawork app though. Let me look into this some more to understand the problem.

**Comment by adamstep** [comment]
We updated our app to use the latest version of Hyperview. We are currently testing the behavior of the back button, if we find any bugs I will update here.

**Comment by terryatgithub** [comment]
hi @adamstep , now we have implemented the effect of "back to previous page and refresh it's content" by using`action=navigate` and `url?timestamp=1234`; 
so this is not urgent. pls note it.
thanks for all your effort.

**Comment by rickheere** [comment]
@terryatgithub Thank this how I now managed to fix this in my app as well.

@adamstep I have to confirm that this is still an issue. I'm on version `0.73.0`

**Comment by adamstep** [comment]
@hgray-instawork can you confirm this is still an issue with the new navigation support you built?

**Comment by hgray-instawork** [comment]
I've confirmed it's still not working. I have added it to the list of demo updates we will address in the near future.

**Comment by rickheere** [comment]
Ooh, I get it now why you mention it is a demo app issue. This is behavior we need to make our self in the Hyperview component's navigation functions correct?

**Comment by hgray-instawork** [comment]
That's correct. However, I do have an update.

I am working on extending the Hyperview demo to illustrate how the new Hyperview Navigation can be implemented using HXML to define a navigator hierarchy. Using the new navigation system, the "back to other" and "close to other" work as expected.

The updated documentation and demo should be released soon as part of the next Hyperview release.

**Comment by hgray-instawork** [comment]
@rickheere , we have released 0.75.0 of Hyperview. This includes a new switch at the top to illustrate using the updated Hyperview Navigator setup. When the switch is enabled, the "close" and "back" navigation behaviors should work as expected.

Stay tuned for more examples in the near future.

**Comment by eazuka** [comment]
Hi @hgray-instawork, it doesn't seem like this new release and feature has been updated to the live document on https://hyperview.org. I have just visited the website doc section to read about the new Navigation implementation but nothing about navigate.

**Comment by hgray-instawork** [comment]
Hi @eazuka, you should be able to see it in the `Reference` section of the site. If you look at the bottom of the sidebar you should see a new "Hyperview Navigation" section. It includes references for the navigator and nav-route components:
- https://hyperview.org/docs/reference_navigator
- https://hyperview.org/docs/reference_nav_route

Regarding examples, there are none posted in the `Examples` section of the site but they are included in the "demo" directory of the source code.

I hope that helps.

**Comment by eazuka** [comment]
Thanks @hgray-instawork. yes i did checked the Reference section but i was expecting to see it under the Display Elements, didn't know it was at the bottom. Thanks for pointing out the location.

**Comment by hgray-instawork** [comment]
Great thanks for confirming @eazuka!
